name: rgbkrk's blog
author: Kyle Kelley
url: http://rgbkrk.github.io

pygments: true
permalink: pretty
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", 'Gemfile', 'Rakefile', "README.md", 'sass', 'watch.sh', 'style.scss']
